baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Your Life Learning'
theme = 'papermod'
[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'bees@hey.com'
    favicon='/static/favicon.ico'